#!/bin/bash

max_try=10

cd "$(dirname "$0")"

echo "------------------------------------" >> log.txt
echo `date` >> log.txt

for (( i=0; i<$max_try; ++i )); do
	systemctl --user is-active --quiet pipewire-pulse
	if [ $? -eq 0 ]; then
		echo 'pipewire-pulse is running: setting up helix virtual sinks' >> log.txt
		echo "------------------------------------" >> log.txt
		echo >> log.txt
		python3 routing.py
		exit 0
	fi
	echo 'Waiting for pipewire-pulse to run' >> log.txt
	sleep 1;
done

echo 'pipewire-pulse is still not running: aborting helix configuration' >> log.txt
echo "------------------------------------" >> log.txt
echo >> log.txt
exit 1

