#!/bin/bash

max_try=10

cd "$(dirname "$0")"

echo >> log.txt
echo "------------------------------------" >> log.txt
echo `date` >> log.txt

is_pipewire_active () {
	systemctl --user is-active --quiet pipewire
	if [ $? -ne 0 ]; then
		echo 'pipewire is not running' >> log.txt
		return 1
	fi

	systemctl --user is-active --quiet pipewire-pulse
	if [ $? -ne 0 ]; then
		echo 'pipewire-pulse is not running' >> log.txt
		return 1
	fi
	return 0
}

for (( i=0; i<$max_try; ++i )); do
	if is_pipewire_active; then
		echo 'pipewire is running: setting up helix virtual sinks' >> log.txt
		echo "------------------------------------" >> log.txt
		python3 routing.py
		exit 0
	fi
	sleep 1;
done

echo 'pipewire-pulse is still not running: aborting helix configuration' >> log.txt
echo "------------------------------------" >> log.txt
exit 1

